### PR TITLE
W r/legacy upload

### PR DESCRIPTION
**Pull request by radiocane**
Add support for legacy upload.

### CODE REVIEW

**Comment by radiocane** [comment]
@iNPUTmice do you have any opinion on this?

**Comment by iNPUTmice** [comment]
How carefully did you test this?
I don't think I have a server that only support the old http upload.

**Comment by radiocane** [comment]
I succesfully tested this with the servers at tracciabi.li and datenknoten.me, they both support only legacy upload.
Looking at https://xmpp.net/directory.php, there is no "legacy only" server among those founded from 1999 until 2003. I could keep on searching for another server if you're not confortable enough to pull this.

**Comment by iNPUTmice** [comment]
Hi,

thank you. This has just been merged into the legacy branch.

**Pull request closed without merging**
