### PR TITLE
Add F-Droid button / link to README.md

### PR DESCRIPTION
**Pull request by ParkerK**
Added a download button for the F-Droid repo to README.md

### CODE REVIEW

**Comment by Natureshadow** [comment]
>/close this, it's not something that needs to be advertised here.

Yes it is. You cannot be serious about privacy and then make people think they need proprietary app stores to install Conversations.

**Comment by d9h02f** [comment]
I still think Conversations should be available at zero monetary cost. Hiding it behind a paywall on proprietary stores convinces no one when it can be gotten for free from F-Droid or Aptoide. All it does is make people less likely to be using the latest version. Not to mention new users get asked to pay again (for a conversations.im account) immediately after installing the application they just paid for.

**Comment by licaon-kter** [comment]
> You cannot be serious about privacy and then make people think they need proprietary app stores to install Conversations.

You cannot be serious about privacy and still use Google products (aka Play store here).
You cannot be serious about privacy and NOT compile you own applications, right?
Github access is Free, Android Studio is free, Linux is free... so yeah... this app is already free.

> Hiding it behind a paywall on proprietary stores convinces no one when it can be gotten for free from F-Droid or Aptoide

Users of said stores can already install it, not sure I follow, do you expect users of Google Play store be informed there they can install it from some place else for free? Users that can open this Github repo are smart enough to find it on F-Droid.

> All it does is make people less likely to be using the latest version.

What do you mean? F-Droid version is up to date, Google Play store version is up to date.

> Not to mention new users get asked to pay again (for a conversations.im account) immediately after installing the application they just paid for.

False, IIRC buying the app gives you 6 months of free conversation.im access. Anyway you are free to use [any other free server out there](https://gultsch.de/compliance.html), because "users that are serious about privacy" know how XMPP works and can find servers.

Again, it's their repo (and let's be honest they do most of the work), they can decide NOT to advertise this here. No problem for me and others to either compile this or just install from F-Droid. All hail GPL-3!

BTW, pretty please, do tell all your "friends that are serious about privacy" about F-Droid. ;)

**Comment by Natureshadow** [comment]
> I still think Conversations should be available at zero monetary cost.
> Hiding it behind a paywall on proprietary stores convinces no one when
> it can be gotten for free from F-Droid or Aptoide. All it does is make
> people less likely to be using the latest version. Not to mention new
> users get asked to pay again (for a conversations.im account)
> immediately after installing the application they just paid for.

I agree. That has been a major issue when trying to convince people to
use XMPP and Conversations.

Normally, it goes like this:

New user: Hey, you said I should use Conversations. But it costs money,
          WhatsApp does not cost money.

Me:       Yeah, you must get it from F-Droid. Install F-Droid first.

(Note that I have lost 50% of new users here.)

New user: OK, cool, here's my JID: xyzbla@conversations.im

Me:       Didn't you say you don't want to pay?

New user: Huh? Pay? Why pay?

Me:       Because you registered with conversations.im, which costs 8 €
          a year. It's written somewhere well-hidden…

(Note that I have lost another 40% of new users here.)

**Comment by licaon-kter** [comment]
Oh these are your "serious about privacy" friends? Wow, ok... nevermind then.

**Comment by iNPUTmice** [comment]
Before this leads to another pointless debate on how I should make a living I'm closing and locking this issue.
The F-Droid build is not signed by myself and thus I'm not linking to it as an official version. Users who already use and trust F-Droid will find Conversations there regardless.

**Pull request closed without merging**
