### PR TITLE
Open and close soft keyboard with dialogs

### PR DESCRIPTION
**Pull request by harshitbansal05**
This pull request aims at opening and closing soft keyboard with `Edit nick` and `Edit Description` dialogs. The keyboard would now open on opening the dialog and close on dismissing.

### CODE REVIEW

**Comment by iNPUTmice** [comment]
There is a bug when i collapse the keyboard and then press cancel the keyboard will re appear

**Comment by harshitbansal05** [comment]
@iNPUTmice I tried to solve that bug, and did that by measuring the height difference when the soft keyboard was shown. It does solve the bug. Unfortunately, I could not find any simple way as there's no proper way to get the window token. So, the only alternative seems to me is wrap it in a `DialogFragment` and get the window token in the destroy callback.

**Comment by harshitbansal05** [comment]
@iNPUTmice could you please review?

**Comment by iNPUTmice** [comment]
1b0e9f2f0d4ea74c1b79be9ee728fbf94d860f60 implements this w/o having to measure screen heights.

**Pull request closed without merging**
