### PR TITLE
[~] scramble JID in logs & close FileInputStream

### LINKED ISSUE #1150: Resource leak -- file not closed -- found by Facebook's static analyzer
Hello,
This resource leak report, included with comments below, were found by running

Facebook's Infer static analyzer on Conversations.

Regards,
Dulma Rodriguez
Facebook Static Analysis Tools Team

File: libs/MemorizingTrustManager/src/de/duenndns/ssl/MemorizingTrustManager.java

Report: Resource Leak: resource acquired by call to FileInputStream(...) at line 329 is not released after line 329.

Remarks: The file should be closed.

---

File: src/main/java/eu/siacs/conversations/persistance/FileBackend.java

Report: Resource Leak: resource acquired by call to FileOutputStream(...) at line 159 is not released after line 171

Remarks:  The calls to os.flush and os.write can throw exceptions, in which case the streams won't get closed.

### LINKED ISSUE #1588: Stop outputing Jabber ID in logcat
A crash in another app will yield a Google Feedback dialog where you can attach a system log.
That system log ( taken as root by the Google Feedback agent? ) has everything in it ( like Wi-Fi SSIDs from around the device which are a privacy bomb on their own anyway ) and unfortunately Conversation outputs connection errors, ping and all in there by mentioning the account in full.

Either stop that all together or (for debugging) let the user give a different alias for accounts and not output Jabber ID directly.

/LE: All these `Log.d(Config.LOGTAG, account.getJid().toBareJid().toString() +` need to be redesigned.

### PR DESCRIPTION
**Pull request by magicbrothers**
Implementation of issue #1588 :
JID test@example.org will be replaced by t***@ e********** in logs.

closes #1588, closes #1150

### CODE REVIEW

**Comment by licaon-kter** [comment]
Thanks for the effort :)

**Comment by magicbrothers** [comment]
...and closes #1150

**Comment by magicbrothers** [comment]
...and closes #1150

**Comment by iNPUTmice** [comment]
Hi,

please keep your PR clean and only address one issue at a time.

Regarding the JID scramble:
* The scrambled JID should be cached (probably in the Account class; when ever the `jid` attribute is set also set a scrambled variant of it.
* Take a look at `Strings.repeat()` for what is probably a more efficient way of writing multiple `*`.

**Comment by magicbrothers** [comment]
Okay, I'll do it again, the JID scramble. Thanks for the help.
(Was my first PR :D)

**Pull request closed without merging**
