### PR TITLE
Added Activity to test Camera using webRTC Library

### PR DESCRIPTION
**Pull request by ElAmin88**
This is a basic implementation to show camera using webRTC Library to apply for the Google summer of code project ,it's the start to implement video calls in the application , you can test it by pressing the Camera button in the activity_conversations menu

### CODE REVIEW

**Comment by ElAmin88** [comment]
I don't understand why it failed the build in the check , can someone specify it ?

**Comment by licaon-kter** [comment]
No source code for `libwebrtc`?

**Comment by ElAmin88** [comment]
I add the library libwebrtc.aar file in the libraries folder

**Comment by licaon-kter** [comment]
The F-Droid build needs the source code for any used library. Eg. From Maven or another repo

**Comment by ElAmin88** [comment]
where should i put the source code after cloning it ?

**Comment by licaon-kter** [comment]
It depends, where does the soirce come from? Does it live in a repo? Can you link to it as a git submodule?

**Comment by ElAmin88** [comment]
This is the source code i found 
https://webrtc.googlesource.com/src

**Comment by SkewedZeppelin** [comment]
Replace
`compile(name:'libwebrtc', ext:'aar')`
with
`implementation 'org.webrtc:google-webrtc:1.0.+'`
and then `rm libs/libwebrtc.aar`
as detailed here https://webrtc.org/native-code/android/#prebuilt-libraries

also why did you remove the debug buildType?

**Comment by ElAmin88** [comment]
I fixed the issues with the build type and used the new library but i still don't know why travis CI build failed !!

**Comment by ElAmin88** [comment]
@sirdrakeistda i was applying for Google summer of code but i was rejected for some reason, so i stoped working on it

**Pull request closed without merging**
