### PR TITLE
Update backup info in Readme 

### PR DESCRIPTION
**Pull request by licaon-kter**

### CODE REVIEW

**Comment by iNPUTmice** [comment]
You don’t need to disable the account beforehand.

**Comment by licaon-kter** [comment]
Yes, maybe, but won't stuff get b0rked if the user backups and then by the nature of chat carries on some chats before moving and restoring?

I thought it's more on the safe side to have them disabled and avoid "accidents"

**Comment by iNPUTmice** [comment]
>  won't stuff get b0rked if the user backups and then by the nature of chat carries on some chats before moving and restoring?

No. That’s why we introduced the backup future only now after the self healing feature.

Also you can remove the old section. Carrying around old information isn’t useful. (Legacy users still find the legacy readme in that branch)

**Comment by licaon-kter** [comment]
Ok, will do asap...

**Comment by licaon-kter** [comment]
Done

**Pull request merged**
