### PR TITLE
discover rooms

### PR DESCRIPTION
**Pull request by ChaosKid42**
This is a simple solution for https://github.com/siacs/Conversations/issues/279.

In Config.java you can list all muc services you want your client to query for rooms. Each found room that is not already in your list of bookmarks is added to it. 

You can also choose to automatically query the muc services on the account's your own server.

### CODE REVIEW

**Comment by myluckyapps** [comment]
@ChaosKid42 , 

I have ported same in changes in pixart and installed apk in two different phones. But one of phone its always crashing with below core: 

```
    java.lang.NoSuchMethodError: No interface method stream()Ljava/util/stream/Stream; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
        at de.pixart.messenger.services.XmppConnectionService.fetchRooms(XmppConnectionService.java:1546)
        at de.pixart.messenger.services.XmppConnectionService$5.onBind(XmppConnectionService.java:309)
        at de.pixart.messenger.xmpp.XmppConnection.finalizeBind(XmppConnection.java:1259)
        at de.pixart.messenger.xmpp.XmppConnection.lambda$sendServiceDiscoveryInfo$3$XmppConnection(XmppConnection.java:1250)
        at de.pixart.messenger.xmpp.XmppConnection$$Lambda$3.onIqPacketReceived(Unknown Source)
        at de.pixart.messenger.xmpp.XmppConnection.processIq(XmppConnection.java:807)
        at de.pixart.messenger.xmpp.XmppConnection.processStream(XmppConnection.java:680)
        at de.pixart.messenger.xmpp.XmppConnection.processStream(XmppConnection.java:541)
        at de.pixart.messenger.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:868)
        at de.pixart.messenger.xmpp.XmppConnection.processStream(XmppConnection.java:525)
        at de.pixart.messenger.xmpp.XmppConnection.connect(XmppConnection.java:440)
        at de.pixart.messenger.xmpp.XmppConnection.run(XmppConnection.java:512)
        at java.lang.Thread.run(Thread.java:818)
```
crash line is:
XmppConnectionService.java:1546  

```
1545:        if (Config.MUC_DISCO_OWN_SERVER) {            
1546: 
 muc_services.addAll(account.getXmppConnection().getMucServers().stream().map(Jid::of).collect(Collectors.toList()));
1547:        }
```
Anything need to fixed? please suggest me. thanks

**Comment by licaon-kter** [comment]
@myluckyapps  Android version? Device name?

**Comment by myluckyapps** [comment]
Problematic Phone details:
1) Android Version: 6.0.1
2) Baseband version: G5510ZCU1APK1
3) Kernal version: 3.18.24-xxxx
4) Model number: SM-G5510 ( Samsung Galaxy On5 2016 Youth)


Working Phone details:
1) Android Version: 7.0
2) Baseband version: G920IDVU3FQD2
3) Kernal version: 3.10.61-xxxx
4) Model number: SM-G920I ( Samsung Galaxy S6)

**Comment by ChaosKid42** [comment]
@myluckyapps Sorry. I don't know what causes this problem.

**Comment by ChaosKid42** [comment]
@myluckyapps I think i fixed the bug. stream() is available since Java 8. Unfortunately Java 8 is supported only from Android 7. This causes the crash.

**Comment by meaz** [comment]
Will this possibility be implemented any soon? That would be really useful!

**Pull request closed without merging**
