### PR TITLE
Minor fixes for the Romanian translation

### PR DESCRIPTION
**Pull request by licaon-kter**
BTW, shouldn't the folder be named `values-ro` ?

### CODE REVIEW

**Comment by strb** [comment]
Hi. First of all, thank you for your contribution! Unfortunately, we can't merge this PR here, because [translations are handled on Transifex](https://github.com/siacs/Conversations#translations). We need the translations to be up to date over there, otherwise they will get overwritten in the future when we re-merge from transifex. It would be really great if you could create an account and submit these fixes over there.

**Comment by andersruneson** [comment]
Is it possible to add in all language files a header with this information?

**Comment by licaon-kter** [comment]
You're lucky it's auths with Github...

**Comment by licaon-kter** [comment]
1 day later, still can't translate.

Can any of you please update it?!

10x

**Comment by iNPUTmice** [comment]
I'm on vacation right now. I won't be able to add you as a translator until
the 23rd

**Comment by licaon-kter** [comment]
Ok, done.

Any time frame (after your vacation that is :D) for the next language merge and/or new release?

**Comment by licaon-kter** [comment]
@iNPUTmice no Transifex pull before 1.7.3 ? :(

**Comment by licaon-kter** [comment]
@iNPUTmice Still no Transifex pull ? :(

**Pull request closed without merging**
