### PR TITLE
Image confirmation feature

### PR DESCRIPTION
**Pull request by daivat15**
Added a feature to confirm all images choosen explicitly before sending them as requested by many users [here](https://github.com/siacs/Conversations/issues/1879).

### CODE REVIEW

**Comment by iNPUTmice** [comment]
Hi,

thank you for your work.

When I envisioned this feature I always imagined that the image preview / confirmation view would take the place of the message input area leaving the conversation visible on top.
This would also solve the main reason a lot of people wan this feature in the first place and that is avoiding sending pictures to the wrong conversations. A separate screen as you do in your PR gives no context to what conversation those images are shared with.

Would you care to rework the PR to show the preview in place of the message input box. (Maybe the send button can stay and act as the confirmation button)

Also keep in mind that this should also work with files shared over the share with activity. And maybe with all kind of files not just images (non images and non videos of course should show some sort of pictogram of course)

**Comment by daivat15** [comment]
@iNPUTmice I am not sure how to implement the image preview/confirmation view. It would be wonderful if you could just guide me as to where I should refer to start reworking on this. This kind of layout building with image previews popping up from below the chatbox is something I have not worked on so far and I am not able to find a suitable resource to start.

**Comment by Kandr0s** [comment]
Add an invisible imageview next to the [EditMessage](https://github.com/siacs/Conversations/blob/master/src/main/res/layout/fragment_conversation.xml#L32).
If you want to upload an image, hide the EditMessage and show the imageview with the image inside.

**Comment by daivat15** [comment]
@iNPUTmice the confirmation feature should be implemented when we choose images or files right? Of course, the file chosen from the system viewer maybe of any type and I'll try to handle that. However, all other cases have been handled as the in built camera/recording apps automatically ask for the users confirmation before sending the file.

**Pull request closed without merging**
