### PR TITLE
Updated Franch translations for typing notifications

### PR DESCRIPTION
**Pull request by QuentinC**
Just new strings on French translations !

### CODE REVIEW

**Comment by iNPUTmice** [comment]
Hi,

would you mind using [transifex](https://www.transifex.com/projects/p/conversations/)? That would make the process a lot easier on my side. Thank you.

**Comment by QuentinC** [comment]
Hi,

Can you add me to the project ?

Thanks !

**Comment by iNPUTmice** [comment]
I just did. Thank you. I'm closing here.

**Comment by QuentinC** [comment]
I've just updated the translations ;-)

**Pull request closed without merging**
