### PR TITLE
Bugfix for issue #1121

### PR DESCRIPTION
**Pull request by lookshe**

### CODE REVIEW

**Comment by iNPUTmice** [comment]
Hi,

if I'm seeing this correctly you are no longer lower casing the path? Thus images with an extension like .JPEG or .JEpg or no longer recognized. Can you make sure they are?
And also can you remove the comment I don't think that this is necessary at that point. Thank you!

**Comment by lookshe** [comment]
I have changed to compare with lowercase.
But I am not willing to remove the comment, because comments are necessary to understand what and why the coding does something.

**Comment by iNPUTmice** [comment]
Ok thank you!

can you change the link to something generic using http://example.com/image.jpg and then squash and rebase this PR?

**Comment by lookshe** [comment]
Hi there,

this was the first time I have done this, hopefully everything is now, as you expected.

**Pull request merged**
