### PR TITLE
Add ignore rule for formal signed builds and Update gradle to 5.4.1

### PR DESCRIPTION
**Pull request by stevenleeS0ht**
Let git ignore the output directory for signed packages.

### CODE REVIEW

**Comment by licaon-kter** [comment]
Why update Gradle in a PR about .gitignore?

**Comment by stevenleeS0ht** [comment]
Sorry, I forget to create a new branch. But it just update gradle, which is not a bad idea.

**Comment by stevenleeS0ht** [comment]
@licaon-kter , these two commits are very simple. This time, I forget. Next time, I will create a new branch. Sorry about that.

**Comment by stevenleeS0ht** [comment]
@licaon-kter  and @iNPUTmice , the old gradle have problem when generating signed package (GC overflow). When update to new gradle version, problem solved.

I was wondering if I should write this as issue. But since It has been resolved. And if I write down the details of that problem. I need to revert to old version (a log inconvenience ).

**Comment by iNPUTmice** [comment]
I've upgraded to the new gradle version locally and the APK files are still in the build directory which is already in the ignore file? Did you build it differently to make the files appear in root?

**Comment by stevenleeS0ht** [comment]
@iNPUTmice , when simply build, it will appears in `build`. But when generate signed package. it will be generated to directories which I mentioned in ignore-rules.

**Comment by iNPUTmice** [comment]
How do you generate the signed package? I'm also building signed APKs and I don’t have that.

**Comment by stevenleeS0ht** [comment]
@iNPUTmice , Build -> Generate Signed Bundle / APKs , then Next -> Next -> finish.

**Comment by iNPUTmice** [comment]
> @iNPUTmice , Build -> Generate Signed Bundle / APKs , then Next -> Next -> finish.

This let's you select a destination folder. So putting something that is user defined into .gitignore doesn’t make sense.

**Comment by stevenleeS0ht** [comment]
Ok, thanks. I didn't notice that.

**Pull request closed without merging**
