### PR TITLE
Added some Chinese translation

### PR DESCRIPTION
**Pull request by SoyaLeaf**
as the title says

### CODE REVIEW

**Comment by licaon-kter** [comment]
Better use the site: https://www.transifex.com/projects/p/conversations/ to update it.

**Comment by SoyaLeaf** [comment]
oh...ok...thanks

**Comment by iNPUTmice** [comment]
Since this PR touches a lot of strings I can make an exception this time and push your strings to transifex. But please use transifex for subsequent changes.

**Comment by SoyaLeaf** [comment]
Thank u... I'm sorry I did not know transifex before,and I'm applying for Conversations in transifex. 
:D

**Comment by iNPUTmice** [comment]
Your changes are part of this commit: 4d7d7623a032c669c41bfa9d49dbacb49c8b2ed7

**Pull request closed without merging**
