### PR TITLE
Add "Select text" context menu option

### PR DESCRIPTION
**Pull request by Mishiranu**
In https://github.com/siacs/Conversations/issues/1615#issuecomment-167341953 user asked about selection option. I think now this option might be helpful when double tap is difficult, for example in case when message consists of only one link.

Unfortunately, Android API doesn't provide a method to start selection manually as you told in https://github.com/siacs/Conversations/issues/1615#issuecomment-167342778, but there is a workaround using Java reflection. I'm using this workaround in my project for 2 years and it behaves reliably. The "select text" menu item will be hidden if workaround doesn't work on a particular device.

### CODE REVIEW

**Comment by iNPUTmice** [comment]
This more or less duplicates the copy text option. What do you think about showing on or the other? Ie only show copy text if select text is not available.

**Comment by Mishiranu** [comment]
I thought about it, but I decided that there will be people who got used to copy faster from context menu.

Also there is a little defect in this selection method (using double tap or this workaround) from Android side: every time you call notifyDataSetChanged of adapter, the selection terminates, so in fast chats it can be annoying. I'll try to fix it later, but I think we should leave both menu items until then.

**Comment by Mishiranu** [comment]
I've made a helper class that retains selection after view updating. When you call `notifyDataSetChanged`, selector will gone for a milliseconds, but it's the only way to do it.

I still don't sure this code will work on 100% devices even if I can get access to `startSelectionActionMode` method, so I think to leave "Copy text" button in place.

**Comment by iNPUTmice** [comment]
> every time you call notifyDataSetChanged of adapter, the selection terminates, so in fast chats it can be annoying. I'll try to fix it later, but I think we should leave both menu items until then.

I wonder if this can be handled by simply not resetting the text of the text view if it hasn't changed.

**Comment by Mishiranu** [comment]
I've already tried to do so, but it didn't work.

**Pull request merged**
