### PR TITLE
Support both new and old http upload namespaces

### PR DESCRIPTION
**Pull request by radiocane**
Again. Tested with the server at tracciabi.li

### CODE REVIEW

**Comment by 111usman** [comment]
I liked this pull request.why not we merge this into master? Thanks

**Comment by iNPUTmice** [comment]
Support for legacy http upload is available in 2.2.2

**Comment by 111usman** [comment]
yes,I know.But that does not work with openfire.But this pull request work correctly with openfire(If i add these changes to older versions of conversations e.g 1.23.8).Please suggest me regarding this...Thanks a lot...

**Comment by licaon-kter** [comment]
@111usman open a new issuo stating app/server versions, modules, xeps, and grab logs

**Pull request closed without merging**
