### PR TITLE
solve formatting issue in conversation list

### PR DESCRIPTION
**Pull request by harshitbansal05**
This pr solves #2705. Thus styling is also applied to the last message preview.

### CODE REVIEW

**Comment by harshitbansal05** [comment]
@licacon-kter could you please review this?

**Comment by licaon-kter** [comment]
Just put a picture...

**Comment by harshitbansal05** [comment]
screenshot_2018-02-23-15-06-19-629_eu siacs conversations
@licaon-kter

**Comment by licaon-kter** [comment]
Great, looks fixed. :)

**Comment by iNPUTmice** [comment]
Can you explain why you switched the view to an EditText? That seems odd considering that the text doesn't need to be edited.

**Comment by harshitbansal05** [comment]
I did it to leave the `MessageEditorStyler` class unaltered. But I think, a better approach would be to unify message styler for edittext and textview @iNPUTmice.

**Comment by harshitbansal05** [comment]
@iNPUTmice is it fine now?

**Comment by licaon-kter** [comment]
What's the status of this?

**Comment by iNPUTmice** [comment]
Fixed in 7ca719b8beec5d8dd8f4b26701143490af4f9186

**Pull request closed without merging**
