### PR TITLE
Add muc search

### PR DESCRIPTION
**Pull request by philipflohr**
This adds muc roomsearch to Conversations.

The roomsearch is implemented as an additional tab in the StartConversation activity

Additional feature: Conversations automatically searches for muc rooms on all servers it discovers
(start a conversation with someone@jabber.ccc.de and wait for about 10 seconds, navigate to the rommsearch -> all rooms on conference.jabber.ccc.de are lsited)

### CODE REVIEW

**Comment by iNPUTmice** [comment]
> (start a conversation with someone@jabber.ccc.de and wait for about 10 seconds, navigate to the rommsearch -> all rooms on conference.jabber.ccc.de are lsited)

I'm honestly not sure if this is a not bit too much. My original concerns (large public servers will give you a huge list of boring rooms with no one in them) are still valid. The recent interest in this feature only comes from the desire of showing a limited number of rooms for people in private networks.

i'm not even sure I want to enable that feature by default... And discovering random servers of random people I chat with won't make the effect of having mostly garbage in there any better.

**Comment by philipflohr** [comment]
As the different leves of discovery are triggered from single places in the code it should be no problem to turn them into settings. 
There are four ways of room discovery:
1. Discover rooms on the server hosting the users account (on login)
2. Discover rooms on servers hosting a conference the user is joining (on joining)
3. Discover rooms on all servers Conversations learns about
4. Discover rooms on servers a user points to in the StartConversationActivity (is this what you thought of?)

point 4 is essential for the usability of this feature, the other ones could be turned into settings the user must first enable.

If this is ok for you I'll change it that way

**Comment by iNPUTmice** [comment]
Actually I was just talking about 1

So you are personally intended this feature more as a fancy auto-complete?

**Comment by philipflohr** [comment]
I think I have quity the same use case like you (private server with some friends and other friends using their own private servers). Each of this servers is hosting a small (<5) amount of conferences.

point 1 is quite nice for small servers but you'll still get the complete list if you have an @jabber.ccc.de account

In my tests the big list of rooms I'll never join was not annoying as the search function is also applied to the conference host (if you enter a small piece of your friends servers hostname you'll only see conferences on this host)

**Comment by philipflohr** [comment]
Reworked this:
It's now possible to select on which servers Conversations searches for new conferences withing the SettingsActivity

Defaults to Search on own server only

**Comment by philipflohr** [comment]
Any news or opinions on this?

**Comment by Natureshadow** [comment]
I like the idea, will try to build and test with our server later.

**Comment by philipflohr** [comment]
You`ll need to do pretty much merging work if you want to use this with the current version of Conversations. If you suceeded please send a pull request to my branch.

Thanks

**Comment by thundergreen** [comment]
This feature still active? Would like to build a conversations Version with it

**Comment by philipflohr** [comment]
@thundergreen I've not been working on this pull request since it was sent in. 
I don't think there have been fundamental changes in message processing since then -> The conflicts should be quite easy to resolve.
Good luck;)

**Comment by egproo** [comment]
**philipflohr** :: thanks very much

**Comment by Aluisyo** [comment]
hi, i like the idea. is it also possible to add code for user search?

**Comment by nioc** [comment]
Hello @iNPUTmice, why do you not merge this feature ? I think it is the easiest way for joining private server room.

**Comment by Fank** [comment]
@philipflohr its a long time ago, but could you try to update the pr and remove conflicts?

**Comment by philipflohr** [comment]
@Fank Sry, no time at the moment to do this.

@iNPUTmice Before someone starts working on this you should make clear if you would add this feature, if there are technical requirements to take care of and what the GUI should look like.

If someone wants to have a look at [the specification](https://xmpp.org/extensions/xep-0045.html#entity)

**Comment by alugarius** [comment]
I would like to donate for this feature

**Comment by iNPUTmice** [comment]
Closing this in favor of a potential future solution based on muclumbus.

**Pull request closed without merging**
