### PR TITLE
refactor code to include jid from babbler

### PR DESCRIPTION
**Pull request by harshitbansal05**
This pull request tries to solve #2717. It refactors the code to include default jid implementation from babbler project instead of own jid class.

### CODE REVIEW

**Comment by iNPUTmice** [comment]
Does the newer version 0.7.5 of the library no longer work?

**Comment by harshitbansal05** [comment]
sorry, I have not tried with it  0.7.5. I would try it now

**Comment by harshitbansal05** [comment]
@iNPUTmice i tried increasing it to 0.7.5. and it worked fine..

**Comment by iNPUTmice** [comment]
> @iNPUTmice i tried increasing it to 0.7.5. and it worked fine..

OK. Thank you.

I'm very interested in merging this Conversations 2.0. Couple of things though.

* I think the JidHelper.fromParts() is unnecessary and can just be replaced with Jid.of(..)
* The InvalidJidException is unnecessary. Instead it should catch the InvalidArgumentException where necessary
* Please rebase this on top of the app_compat branch. That branch has the OtrService removed and makes a few helper functions like the fromSession() obsolete.
* isDomainJid() and hasLocalpart helper functions are probably also obsolete. Just use jid.getLocal() != null in the code.

**Comment by SoyaLeaf** [comment]
Can you compile successfully? I failed...maybe I'm missing configuration.. :(

**Comment by harshitbansal05** [comment]
@SoyaLeaf yes..

**Comment by harshitbansal05** [comment]
@iNPUTmice should I close this pr and instead make a pull request on `app_compat` branch?

**Comment by harshitbansal05** [comment]
@iNPUTmice ^^

**Comment by iNPUTmice** [comment]
This has been merged into the app_compat branch.

**Pull request closed without merging**
