### PR TITLE
(WIP, do not merge) New PGP Implementation (XEP-0374)

### PR DESCRIPTION
**Pull request by adithyaphilip**
This PR aims to add support for the new PGP XEP ([XEP-0374](https://xmpp.org/extensions/xep-0374.html)).

@dschuermann @valodim
Available as new option `OpenPgp (OX)` under the select encryption icon in a conversation.
Currently implemented:
- [x] Sending and receiving encryted and signed signcrypt messages in Base64 encoding.
- [x] Verification of signature of received message.

Key announcement currently piggy-backs on the announcement mechanism for XEP-0027.
Todo:
- [ ] Switch to public PEP node for public key announcement.
- [ ] Synchronization of private key using private PEP node.
- [ ] Mechanism to automatically add to existing/create new key with with `xmpp:user@example.org` as the userid.

Currently implemented features should allow messages to be exchanged between contacts, open to testing.

### CODE REVIEW

**Comment by devurandom** [comment]
Is this about XEP-0374 (#2196)?

**Comment by adithyaphilip** [comment]
@devurandom Yes, it is. Unfortunately work got in the way of this being completed at the time, though I do intend to return to this at one point.

**Comment by devurandom** [comment]
Could you please adjust the summary to make it clear what XEP you are referring to, making it easier for people to find this PR using the search?

**Comment by adithyaphilip** [comment]
@devurandom good call, edited the title and summary to include the specific XEP and link.

**Comment by iNPUTmice** [comment]
I’m closing this due to inactivity.

**Pull request closed without merging**
