### PR TITLE
Added search functionality for chats (Fixes #1315)

### LINKED ISSUE #1315: Feature request: Message search
It would be nice if you could search for messages within conversations, similar to the search feature for the contact list.

I posted a [Bounty for this feature](https://www.bountysource.com/issues/25371199-feature-request-message-search).

### PR DESCRIPTION
**Pull request by vanitasvitae**
This is very untested, but I'd like to get some feedback :)

### CODE REVIEW

**Comment by vanitasvitae** [comment]
There are still some bugs (menu entry appears in chat overview)

**Comment by daniel-dona** [comment]
A proper search function is the most useful feature that Conversations lacks nowadays. But is not a problem in Conversations, XMPP has not standard way for history search.

So, I think we have more than one thing to develop/fix:

- Proper XEP for history search: maybe XEP-313 (MAM) can work, but the search field is optional and I don't know witch servers do actually implement it. 
(See sections 4.1 and 4.2 https://xmpp.org/extensions/xep-0313.html)

- Proper search in Conversations history: this PR only search in the messages displayed in a particular conversation. If I close that conversation and open it again, the older messages (already downloaded with MAM in the past, already in the Conversations history) are not shown and not searchable. 
Then, on the basis of a working XMPP/XEP/MAM search feature, combine server side and client (history) side search.

If OMEMO is in use, the only way of searching in the content of the messages is to do it in Conversations, so maybe a "download full history" (or "last 3 months", or "full xxxx@xxx.im conversation", etc...) option would be a good idea too.

I know it is a complex issue, but an "almost text" communication way -with a history functionality- but without a proper search functionality is a nonsense.

**Comment by petmue** [comment]
Is there any reason why this PR has not been merged yet? Thanks!

**Comment by vanitasvitae** [comment]
Not from my side. I haven't touched the code anymore since I opened the PR.

**Comment by licaon-kter** [comment]
This was stopped? Rejected? What's the story?

**Comment by vanitasvitae** [comment]
The code is not very tested and I'm sure there are better ways to solve the problem. I haven't received any comments on this PR too, so I don't know if its worth putting more effort into it.

**Comment by jhass** [comment]
I think a local search (that searches through the entire local history in the database) would be awesome, useful on its own, not only to figure out the right UX for such a feature, but also as a basis for then supporting any emerging standards for server side/supported search.

To me supporting server side search is really just an iteration of a search feature, not a requirement to it at all.

**Comment by bhuvi8** [comment]
I think this is very useful feature to have a local search...even without the complications of searching  messages from the server...you could just download archives from the server manually and do local search.
It is better to not complicate the search feature to look for messages in the server

**Comment by iNPUTmice** [comment]
Implemented in 2.2

**Pull request closed without merging**
