### PR TITLE
Show own avatar in tile for conferences with only one other occupant next to theirs

### PR DESCRIPTION
**Pull request by fiaxh**
For conferences with only one other occupant, their avatar is shown as the conference tile. This makes it hard to distinguish conferences from one-to-one chats just by looking at the tile. It is especially a problem when an one-to-one chat with the same contact occupying the conference is also in the list .

This commit tries to improve this by putting the own avatar next to the contacts' one in the conference tile. An argument against this would be, that obviously one is part of every conversation one is in. However, the following point of view makes it look more plausible: Conference tiles represent a room of people where everyone can talk with everyone and you are just one of them.

### CODE REVIEW

**Comment by andersruneson** [comment]
Really good idea, I also have the same problem with some mucs with only me
and another participant and it makes it hard to distinguish from the
one-on-one chat with that person.

I'm not sure putting your own avatar in there is the ideal solution but I
have not come up with a better one!

**Comment by kriztan** [comment]
Nice work. The best would be to set an avatar for a conference like it's realised by Whatsapp

**Comment by andersruneson** [comment]
I don't know WhatsApp, do you have any screenshot?

**Comment by kriztan** [comment]
Sorry, I didn't have Whatsapp installed on my phone. I'll try to get a screenshot from a friends mobile phone. In Whatsapp you can set an avatar in the conference details, like we can set a MUC name in Conversations.

**Comment by kriztan** [comment]
@andersruneson I've looked into Whatsapp today, but there is not realy anything to screen shot. In the conference details you have the possibility to set a conference avatar next to the conference name. But as I can see it in the XEPs, there is no "official" possibility to do that. Perhaps ist could be realised by PEP like user avatars (https://community.igniterealtime.org/thread/51906), but this would only work for Conversations...

**Pull request merged**
