### PR TITLE
Hide account selection spinner for single accounts

### PR DESCRIPTION
**Pull request by af8a524db1**

### CODE REVIEW

**Comment by stevenroose** [comment]
What account selection spinner? I'm single account and never had to select my account, except when going to the accounts menu..

**Comment by licaon-kter** [comment]
@stevenroose Try to add a contact

**Comment by stevenroose** [comment]
Oh that drop down? Hmm yeah I'm not bothered by it. I'd be ok with hiding
it as well, though.

**Comment by iNPUTmice** [comment]
I don’t think making UI elements disappear under unclear conditions is going to help the user.

**Pull request closed without merging**
