### PR TITLE
Keep draft even when correcting previously sent message

### PR DESCRIPTION
**Pull request by singhalok641**
Please review this PR #2329 #1822

### CODE REVIEW

**Comment by iNPUTmice** [comment]
The `EditText` is getting cleared after sending a message in a method called `messageSent()`. You might want to do the swapback to the draft message in there as well. Otherwise there might be race conditions when sending PGP encrypted messages.

**Comment by singhalok641** [comment]
Yes , you are right , I missed that :) . Will do it.

Thanks

**Comment by singhalok641** [comment]
I have made the changes in this pull request by squashing the commit.

**Comment by iNPUTmice** [comment]
A few minor nitpicks
1) I prefer `if (condition) {` The curly bracket in the same line.
2) Don't trim the message before saving it. If the user was about to start a new word we should keep it this way.

**Comment by singhalok641** [comment]
Made changes. :+1:

**Comment by iNPUTmice** [comment]
The message also needs to be restored when hitting the cancel edit button.

**Comment by iNPUTmice** [comment]
I actually spotted a slight logic error in my own code as well and fixed that.
You can now use `if (setCorrectingMessage(null) { restore pervious draft}` The method will return true if you are overwriting the correcting message with null.

**Comment by singhalok641** [comment]
The branch now shows conflicts . How should I resolve them?

**Comment by singhalok641** [comment]
and I didn't get the last comment you have mentioned. The setCorrectingMessage() sets the result and it does return anything, right ?so, how would it return true ? And what changes have you made ? Do I need to pull first ?

**Comment by hareshkh** [comment]
@singhalok641, The master branch of this repo has moved ahead from your fork. That is why you are facing merge conflicts. In order to resolve the merge conflicts, the following should work : 
 - Make a new branch
 - Reset your local `master` branch. The new branch would retain your commits.
 - Then `rebase` the new branch onto the fetched `master`.
 - Then do a `fast-forward` merge of the new branch you created into master.
 - Following this you can force push your local `master` branch to your fork.

**Comment by iNPUTmice** [comment]
Yes you need to pull first. And then setCorrectingMessage will return true after correcting a message.

**Comment by singhalok641** [comment]
not able to reset my branch.
I executed these commands:
git fetch  https://github.com/siacs/Conversations.git master
git reset --hard origin/master
I get this message : HEAD is now at 6718526 Keep draft even when correcting previously sent message

**Comment by hareshkh** [comment]
According to the network graph the base of your branch is `c7ec82679f34888ded83758d7a3a5b0c03830b58`. Try resettting to here. Make sure to make a branch to store your commit or you may loose your commits.

**Comment by singhalok641** [comment]
thanks @hareshkh  and @iNPUTmice

**Comment by singhalok641** [comment]
@iNPUTmice I have made changes for the cancel button. But I didn't understand that how a setter(setCorrectingMessage()) would return true. I have made my changes and the code works fine.
Making commit in few minutes.

**Comment by singhalok641** [comment]
@hareshkh I guess resetting part didn't work.

**Comment by hareshkh** [comment]
@singhalok641 : can you run `pip install yolog` and then run `yolog` and post the output here, after taking a screenshot.

**Comment by hareshkh** [comment]
@singhalok641 : Did you make a new branch? And then reset your local master branch?

**Comment by singhalok641** [comment]
Yes

**Comment by hareshkh** [comment]
selection_002

@singhalok641, according to this it seems like you have made a new branch `develop` and then made a new commit on it altogether. Now to fix this, does the code on your develop branch the latest one and works fine?

**Comment by singhalok641** [comment]
yes , it does . I created it so that I would make a new PR with this branch. But it has conflicts.

**Comment by hareshkh** [comment]
- `git checkout master`
 - `git reset --hard HEAD~1`
 - `git remote add upstream https://github.com/siacs/Conversations.git` ( Do this if you have not already made a remote )
 - `git pull upstream master`
 - `git checkout develop`
 - `git rebase -i master` (This starts a interactive rebase) (On running this command it will apply all commits one by one, make sure you resolve conflicts arriving at each step and then run `git add .` followed by `git rebase --continue` )
 - `git checkout master`
 - `git merge develop`
 - `git branch -d develop`
 - ` git push origin master --force`

Following the above steps will possibly solve the problem you are facing.

**Comment by singhalok641** [comment]
@hareshkh Thanks a lot. Helped me successfully rebase and understand the commands. :)

**Comment by singhalok641** [comment]
@iNPUTmice did you mean this : if(conversation.setCorrectingMessage(null)) {
									mEditMessage.getEditableText().append(conversation.getDraftMessage());
								}
								conversation.setDraftMessage(null);

**Comment by singhalok641** [comment]
I have done draft restoration for the cancel button too.

**Comment by hareshkh** [comment]
@singhalok641, You may consider deleting you develop branch on GitHub. It is redundant now.

**Comment by singhalok641** [comment]
@hareshkh : :+1:

**Comment by iNPUTmice** [comment]
Hi,

thank you for your work. While reviewing your commit I discovered to of my own bugs in the message correction logic; made some small changes and committed all them into cb203f5fd3813b920dc5912bcd4c6e8e595e2169

Your code was fine though. The only remark I had was that after pressing the sent button the message should not be swapped back but only after the message has actually be sent. That was just about removing those three lines and I didn't want to bother you with removing them yourself.

**Comment by singhalok641** [comment]
@iNPUTmice So is this code not okay to be merged ?

**Comment by iNPUTmice** [comment]
@singhalok641 i merged it in the cb203f5fd3813b920dc5912bcd4c6e8e595e2169 commit. I'll consider it merged. Just point to this PR when submitting your application.

**Comment by singhalok641** [comment]
Can I pick more g-soc teaser bugs to solve ? I am really learning a lot and wish to contribute more.

Thanks

**Comment by iNPUTmice** [comment]
Maybe #1490? There are currently not many more issues marked as teaser-task. Maybe I'll go over the bug tracker later and mark a few more.

**Pull request closed without merging**
