### PR TITLE
Per-conference notification options; incl. a new configurable keyword notification method

### PR DESCRIPTION
**Pull request by Natanji**
Implemented a new feature that lets users change notification settings on a per-conference basis: "Default (global)" is the same option as before, but now users may also choose "notify on all messages", "no notifications", "notify when my username is mentioned" and a completely new option "notify when a keyword is mentioned".
The options can be set in the ConferenceDetailsActivity, including editing the keyword list there. The keyword input field is auto-completed with keywords already set in other conferences.
This can also be seen as a fix for #629 and #735; it is also now possible to permanently disable notifications for a conference without triggering the snackbar.

The other commit fixes a small issue with the quickEdit dialogue, in which the keyboard is still displayed on-screen even after an input was validated or cancelled, leading to a suboptimal UX.

### CODE REVIEW

**Comment by Natanji** [comment]
Hey @iNPUTmice, could you please offer some sort of explanation on why you closed this without any comment whatsoever, especially when it's been sitting around here for half a year and fixes two open issues? This totally means no sense to me, especially after we talked on Jabber beforehand and I discussed with you about how to implement these features.

**Comment by iNPUTmice** [comment]
Sorry this has been closed automatically by github when I deleted the development branch. (We will do future development right in the master branch and just tag releases)

**Comment by Natanji** [comment]
Whoups, okay.
While we're at it, is this feature generally still wanted? I know that due to the changes to anonymous MUC notifications, I'd probably have to rewrite a part of it for the merge. But maybe first tell me if the solution I found for these issues is what you want, and if you would merge it, so I don't work for nothing? You can check out https://github.com/natanji/conversations for that. I think it would be great if you'd generally decide about pull requests a liiiittle faster, there should not be a problem either merging or rejecting them within 1-2 months ;)

**Comment by Natanji** [comment]
@iNPUTmice, some answer would be really very much appreciated. :)

**Pull request closed without merging**
