### PR TITLE
Added features of ScanActivity

### PR DESCRIPTION
**Pull request by SoyaLeaf**
Related #2977 
1. Select a QR code image from the gallery
2. Add button to turn on flash in dark environment

Sorry，I merged into the same commit, hope this does not affect the review.

### CODE REVIEW

**Comment by thevietnamm** [comment]
how to compile tis comint?, sorry my bad english but i compiled te last update of conversatios buy y dont see this new funtion.

**Comment by SoyaLeaf** [comment]
@thevietnamm 
Hi, it needs to be merged.
Otherwise, it will not appear in the code of the master branch.

**Comment by thevietnamm** [comment]
I am really new to this, they could advise me, thank you very much and greetings from Colombia

**Comment by licaon-kter** [comment]
@thevietnamm 
`git clone https://github.com/SoyaLeaf/Conversations qr_code`
`cd qr_code`
`git checkout  qr_code`

Then compile...

**Comment by thevietnamm** [comment]
i dont understand , if only i want this merged, but in the fresh repository is say  https://github.com/siacs/Conversations , i using android studio windows , but i dont know how to combine two repositorys , is hard be new in this. If anyone from this team can help me via teamviewer or anydesk, I will be very grateful

**Comment by thevietnamm** [comment]
many many thanks to all those who helped me, could I communicate via PM with any of you to ask you some questions ?, not to make so many comments.

**Comment by thevietnamm** [comment]
i compiled with this diff and i see this 
screenshot_20180425-101951
 but i dont see this 
captura , i dont know if i make somthing wrong. thanks so much for help

**Comment by SoyaLeaf** [comment]
@thevietnamm 

> but i dont see this

Hi, it will appear in a dark environment and you can try to cover the front camera (light sensor).

**Comment by thevietnamm** [comment]
Yes I'm so nob in this, is posible change the share location openstreetmaps to Google maps, I saw that this plugin was incorporated but no with Google maps
screenshot_20180425-220917 thanks so much for your help

**Comment by licaon-kter** [comment]
@thevietnamm it could but it's designed so it does not depend on Google services.

Install https://play.google.com/store/apps/details?id=eu.siacs.conversations.sharelocation and select it as the default provider when asked.

**Comment by thevietnamm** [comment]
thanks so much for the help , I do not know how I can synchronize my project with that of github without writing about what I have already modified, could anyone help me?

**Comment by thevietnamm** [comment]
but if i developing in andoid studio?

**Comment by SoyaLeaf** [comment]
@thevietnamm 
You can operate in git base and it will load automatically in Android Studio.
Or resolve the conflict in Android Studio.
https://www.jetbrains.com/help/idea/resolving-conflicts.html

**Comment by thevietnamm** [comment]
@SoyaLeaf thanks alot , and thanks to all, Sorry to be annoying, but I would like to know if it is possible to change the maps of share location to those of google maps and if it is not possible to disable the location sharing plugin and you the external plugin

**Comment by licaon-kter** [comment]
@thevietnamm See the source of the plugin linked above: https://github.com/siacs/ShareLocationPlugin

Then adapt that...

**Comment by iNPUTmice** [comment]
I don’t think the actual Scan View is a good place for those. If anything one could think about putting them in a menu that appears when clicking the scan button.

**Pull request closed without merging**
