### PR TITLE
Added Background Color change on Conversation Activity

### PR DESCRIPTION
**Pull request by ZeCarlosCoutinho**
In order to complete an University Project, I've added the option, in the Conversation Activity, to change the secondary background color.

- It only has the default("grey") color + blue + red, and they change to a darker tone if the theme is set to "Dark".
- The color type keeps the same even if the theme is changed or larger fonts mode is activated.
- The color keeps even if the app is restarted.

This was done because there was an issue ( #2110 ) mentioning the possibility of background pictures being added to the conversations.
I did not have the time to try to add images, but I could add the option to choose the color, so I did it.

### CODE REVIEW

**Comment by licaon-kter** [comment]
Pics?

**Comment by ZeCarlosCoutinho** [comment]
Here is the imgur link with the photos:
http://imgur.com/a/OzYXT

**Comment by licaon-kter** [comment]
Don't mind me, but I find them unattractive. :-/
While the 2 current themes would not win any artsy contest at least they're build to fit, these backgrounds feel garrish.

**Comment by BlauerHunger** [comment]
While the idea is really nice, not everybody likes the same colors. What about adding a color picker, for example like this: 
w3schools Colorpicker

**Comment by ZeCarlosCoutinho** [comment]
@BlauerHunger Well, in the middle of all the projects I had, this was only a 2-day work :P
(My original intention was to give the ability to pick an image, and set it as background, but I seemed too complex for me to do it in 2 days only)
However, having a color picker is not a bad idea :) 
I had some trouble doing the color change, because the only solution i found was having all the options as styles in the xml, seeming a bit hardcoded, which (i think) isn't a very good programming practice.

@licaon-kter Maybe that's because changing only the secondary background color isn't enough. If I changed the primary colour + the color of the bar on top, it would be more aesthetic. Still, I don't mind if you don't like it. I didn't think the colors were bad, but maybe this feature could be improved to fit in the app "color context".

Now i'm a little busy with some other (and more critical for me) projects, so I won't be changing this for a while.
Still, this is a very secondary feature for the app, so I don't believe this will be much of a problem :P

**Comment by licaon-kter** [comment]
Did you see QKSMS? It has a pretty nice theme selector, if license and time permits, I would like having that brought here.

**Pull request closed without merging**
