### PR TITLE
view animated GIFs inline

### LINKED ISSUE #1939: support for inline animated gifs
It would be nice if animated gifs shared in a conversation would be shown directly inline. at the moment an animated gif get's converted to jpg and shared ad jpg.

### PR DESCRIPTION
**Pull request by illegalprime**
As discussed in #2217, this is the second PR that adds support for viewing animated GIFs in
the message, without leaving conversations.
Fixes #1939

### CODE REVIEW

**Comment by illegalprime** [comment]
@iNPUTmice what changes would you like to see in this PR?
I was thinking you wanted some UI that says "This is a GIF with `x KB` , do you want to download it?"
and then a "Play / Pause" button somewhere.

**Comment by alexara** [comment]
> and then a "Play / Pause" button somewhere.
I'd suggest a transparent "play button" overlay on the image as "nine gag" has it. A double click could play it full screen.

**Comment by illegalprime** [comment]
@iNPUTmice I added a play button and double click for full screen as @alexara described.
But I think you added a "GIF" label that might be clobbered by this play button, so let me know how
you want that. Also, travis says that Android 25 isn't installed.

**Comment by illegalprime** [comment]
@iNPUTmice is there anything more I need to do to complete the PR?

**Comment by muelli** [comment]
@illegalprime  seems like the conflicts need to be resolved.

**Comment by illegalprime** [comment]
@aslmx I don't have the time currently to fix the merge conflicts. :cry:

**Comment by aslmx** [comment]
time will come... :(  patience is a virtue

**Comment by juliusczar** [comment]
hej @illegalprime i almost resolved all conflicts (here: https://github.com/juliusczar/Conversations/tree/feature-inlinegifs), besides one little part in the MessageAdapter.java in 'public View getView' - (but maybe your time allows to have  a look on this - i think its a piece of cake :) )

i dont know how to best proceed here, maybe you can update this PR - or, if your time doesnt allow it, should i open a new PR?

thanks for your work mate - hope we can cross the finishing line 😄

**Comment by luchmhor** [comment]
Any news on that? Would like to see this working soon :)

**Comment by invisiblek** [comment]
rebased on latest master as of today and squashed in to one commit here: https://github.com/invisiblek/Conversations/commits/animated_gifs

**Comment by licaon-kter** [comment]
@invisiblek open a PR then?

**Comment by iNPUTmice** [comment]
Hi,

here are a coulple of problems I have with that commit (in no particular order)

* When the screen gets refreshed (for example after a new messages) a new gif drawable is created an the playing is stopped (because the later happens when it is reloaded - otherwise it would probably start to play from beginning). There needs to be a mechanism to detect what is already in the view and not reload it.
* It looks like the GifDrawable is loaded (from disk) and created on the UI thread. This needs to happen in the background just like normal messages. (Probably best to reuse/extend the current loading mechanism)
* The play button doesn’t adapt to be black or white depending on the image color. I kinda like the way gifs are displayed right now (with the semi translucent GIF tag). It would be nice if we could keep that look and just add touch to play / touch to stop without changing that look

**Comment by invisiblek** [comment]
So I wasn't really planning to get in to this game of improving/reviewing this patch set. I rebased it so it's usable on top of the latest code base, if someone wants to improve it and submit as a new PR, have at it. I likely won't get around to doing that for quite some time.

**Comment by iNPUTmice** [comment]
@invisiblek ok no worries. I just wanted to answer the *why hasn’t this been merged* question ahead of time. Maybe the original developer or someone else wants to take a look at it.

**Comment by Echolon** [comment]
@illegalprime 
Hi, have you considered taking a look again to the mentioned issued with the PR?

Would be nice to have GIFs inline

**Comment by iNPUTmice** [comment]
For now I would like to stop pulling in third party libraries for minor features.

**Pull request closed without merging**
