### PR TITLE
add reply support for android wear

### PR DESCRIPTION
**Pull request by marcelloceschia**
add basic android wear support, to reply from watch

### CODE REVIEW

**Comment by iNPUTmice** [comment]
I'm wondering if it might be better to send the intent to the service instead of the activity. this avoids opening the activity for basically no reason.

**Comment by marcelloceschia** [comment]
Wir können das auch anpassen, einfach sagen was die Präferenzen sind.

**Comment by iNPUTmice** [comment]
This should be working in HEAD.

**Comment by marcelloceschia** [comment]
@iNPUTmice Danke, werde ich testen. Thank you, I'm will give it a try.

**Pull request closed without merging**
