### PR TITLE
Show an Icon in the Conversations List if last Message was a Location/Voice/File

### PR DESCRIPTION
**Pull request by Kandr0s**
screenshot_20171102-092834
screenshot_20171106-153917

### CODE REVIEW

**Comment by iNPUTmice** [comment]
I like the idea. But from looking at the code this doesn't seem to work with theming (dark theme)

**Comment by VoigtK** [comment]
Indeed, i forgot that. I can fix this on Monday.

**Comment by Kandr0s** [comment]
Indeed, i forgot that. I can fix this on Monday.

**Comment by Kandr0s** [comment]
I added Theming and reversed the order. Voice was treated as a File before.

**Comment by uchchishta** [comment]
The location icon is darker than the file icon

**Comment by Kandr0s** [comment]
If you look at the code, you can see that im just using the existing drawables and not adding any new one.

**Comment by iNPUTmice** [comment]
Hi,

can you squash this into one commit?

**Comment by Kandr0s** [comment]
I squashed it.

**Pull request merged**
