### PR TITLE
support contact shortcuts

### PR DESCRIPTION
**Pull request by SoyaLeaf**
Related issues #2823
It supports most Android devices instead of android N_MR1 or higher.
But now it doesn't support open group chat, if it is necessary I can try to do it

show 1

### CODE REVIEW

**Comment by iNPUTmice** [comment]
Cool. I didn’t know that was even possible. You should make the ShortcutActivity extend ListItemActivity directly though. Then you a) don’t have to deal with binding to the service yourself b) don’t have to call yet another activity to select the contact.
Have a look at the contact chooser activity on how to load contacts into a ListItemActivity.

**Comment by SoyaLeaf** [comment]
Thanks for your suggestion, I updated it. : )

**Comment by iNPUTmice** [comment]
This already looks quite nice. Thanks. I really didn’t know this was even possible.
Two remarks though:
1) Can we render the app icon in the corner of the icon?
2) When adding the widget the widget is called 'Conversations 1x1' which seems to be the default name. Can we give that a different name? Maybe 'Contact 1x1'

**Comment by SoyaLeaf** [comment]
Well, that seems to be possible. I've seen it on other apps, and I can try it in my spare time. :P

@iNPUTmice

**Comment by SoyaLeaf** [comment]
Hi, I tried to do it and then it looks like this now (on devices with Android 6.0)，
image

but on my other device (Nokia6 with Android 8.0) it is like this,
image

It is not the same as the newly added shortcut on Oreo. I feel the white border is a little strange. Do we need to find a way to reduce it? @iNPUTmice

**Comment by iNPUTmice** [comment]
> It is not the same as the newly added shortcut on Oreo. I feel the white border is a little strange. Do we need to find a way to reduce it? @iNPUTmice

Yes it's strange but I'm afraid there isn't anything we can do about that. Feel free to try though

**Comment by iNPUTmice** [comment]
How do other widgets for example the regular contact widget look like on your Nokia 6?

**Comment by SoyaLeaf** [comment]
I am sorry that there have been some things in the university that need to be completed recently, so that I did not try enough yesterday. But today I found out that API26 provides new method to help us create widget. Now it looks normal on Android O, just like shortcuts created in other ways.

**Comment by iNPUTmice** [comment]
Hi,

can we render the Conversations icon a bit smaller. Maybe 1/3 of the height of the contact picture. (Instead of 1/2).
Also the widget should be called 'Contact' and not 'Contacts' (you might need a new string for that)

**Comment by SoyaLeaf** [comment]
I updated it. :)
Is there anything wrong with it now?

**Pull request merged**
