### PR TITLE
Allow entering a JID from "choose contact"

### PR DESCRIPTION
**Pull request by singpolyma**
This allows inviting to a MUC any jid, and not just someone from your roster, etc.  Refactored to use the same dialog as "create contact" does.

Closes https://github.com/siacs/Conversations/issues/1602

### CODE REVIEW

**Comment by iNPUTmice** [comment]
Hi,

when entering a jid to invite to a muc we don't need to display the account
spinner. The information won't be used anyway since the muc service will do
the inviting.
I would further suggest not to show the 'enter jid' in every choose contact
activity but only in the one used for mucs. This means when starting the
activity the calling activity should add a 'show enter jid' boolean to the
intent.

**Comment by singpolyma** [comment]
@iNPUTmice updated the pull request per your feedback

**Comment by iNPUTmice** [comment]
Seems to be working. But on android >=L the icon should be the material one. (Compare that to the StartConversationsActivity where the menu uses two different icons as well.)

**Comment by iNPUTmice** [comment]
It might make sense to add the 'Enter Contact' menu item to the menu file with visable=false and just change the visibility when needed instead of trying to create the menu item programmaticlly.

**Comment by iNPUTmice** [comment]
If thats ok with you I'm gonna quickly do the changes myself. I want to include this into 1.8.4 and put that release out of the door rather soon.

Thank you for your work

**Comment by singpolyma** [comment]
Sure, sounds fine to me :)  Thanks

**Pull request closed without merging**
