### PR TITLE
add emoji button

### PR DESCRIPTION
**Pull request by SoyaLeaf**
related #2759 

emoji

### CODE REVIEW

**Comment by wurstsalat3000** [comment]
Would it be possible to display the emoticons with smaller margins? Or to display emoticons in this pane smaller alltogether?

Thanks for your work!

**Comment by SoyaLeaf** [comment]
I'm happy to work for this, but I'm sorry that there seems to be no standard that I can't make the exact adjustment. @wurstsalat3000

**Comment by myluckyapps** [comment]
Is it possible to have below
1) additional tab to show recently or frequently used emojis
2) bottom sheet/layout to have "back press" button to delete last typed emoji[ instead of switching back to textboard to delet last typed emoji]

**Comment by myluckyapps** [comment]
One Android technical help please[ sorry I am very new to Android]:

what configuration or code need to be modified to increase number emojitan tabs within on screen? at this moment 5 tabs are being shown but I wanted to increase these to 8 columns. which part of file/code is responsible for that? thanks for your help in advance.

**Comment by SoyaLeaf** [comment]
> Is it possible to have below

> additional tab to show recently or frequently used emojis
> bottom sheet/layout to have "back press" button to delete last typed emoji[ instead of switching back to textboard to delet last typed emoji]

Yup, this can be achieved. 
But sorry, I did not plan to update this part of code recently. 
I am preparing to take the final exam... :-)

**Comment by dermitdemdino** [comment]
I don't have an Emoij button.

Android: 6.0
Conversations: 2.2.9+fcr

**Comment by licaon-kter** [comment]
@dermitdemdino Change your keyboard app

**Comment by dermitdemdino** [comment]
@licaon-kter That's it, thanks.  Sometimes you have a board in front of your head :-)

**Comment by iNPUTmice** [comment]
I have implemented this in a commercial fork of Conversations and decided that this is a rabbit hole I don’t want to climb into for mainline. It is a pain in the ass to keep all the emojis up to date. The fitzpatrick selection UI is non existence. The keyboard hight calculation doesn’t work in all cases. And it will just be a nightmare to maintain.

**Pull request closed without merging**
