### PR TITLE
Receipts for private  muc-msgs & update last seen from muc msgs

### PR DESCRIPTION
**Pull request by BrianBlade**
Patches for muc related bugs from the todo list.

### CODE REVIEW

**Comment by iNPUTmice** [comment]
Hi,

thank you very much for your work.

Are you interested in the GSOC are did you just do the TODO stuff for fun?

Couple of small comments.
* We use tabs for indention
* I think the two updateLastseen can me merged in parts. (One of the methods can call the other)
* The `if (conversation.getMucOptions().nonanonymous()) {` is unecssary. A truecounterpart != null check is sufficant. This way this will also work in chats that are anonymous but where the user for gets the real jid for other reasons.  (being a moderator)

can you squash this into a single commit once you are done? Thank you!

**Comment by BrianBlade** [comment]
Hi, 

Thanks for your comments.

>Are you interested in the GSOC are did you just do the TODO stuff for fun?

Actually I would love to see Axolotl coming to XMPP and would be more than happy if I can help throughout. But, to be honest, I didnt realize that the todo list was explicitly meant for GSOC participants and I have little Java and hardly any Android experience. So take this as a yes, I would be interested but have not really thought about it nor read the requirements etc.

>Couple of small comments.

>    We use tabs for indention

sorry, just getting comfortable with the IDE which kept replacing tabs with spaces 

>    I think the two updateLastseen can me merged in parts. (One of the methods can call the other)

I tried to overload the updateLastseen() in the new commit (see below), hope that is what you meant?

>can you squash this into a single commit once you are done? Thank you!

I couldnt figure how to squash the commits and push again afterwards. Therefore I created a new branch w/ a single commit: https://github.com/siacs/Conversations/commit/587e796fcddab32a8d792690bd0d26e2c9c568e9
If you would like me to create a new PR simply close this one. Also, if you know a way how I should have updated this pull request I'd be glad to hear about it!

**Comment by SamWhited** [comment]
> I couldnt figure how to squash the commits and push again afterwards. Therefore I created a new branch w/ a single commit

Interactive rebase is your friend. Check out `git rebase -i`, then rewrite history with `git push --force` (never do this on a branch that other people are also working on... in fact, generally double check everything before you do a force push, lest you destroy something you need).

**Comment by BrianBlade** [comment]
@SamWhited Thanks, I was not aware of the --force option.
However, I still dont get it right and dont want to risk messing around so I will just close this PR and open a new one. Sorry for the confusion.

**Pull request closed without merging**
