### PR TITLE
Let users crop their avatar images using the android-crop library

### PR DESCRIPTION
**Pull request by philipflohr**
implements #1534 using the android-crop library
https://github.com/jdamcd/android-crop

This lets users crop their images instead of automatically cropping them.

### CODE REVIEW

**Comment by DoM1niC** [comment]
THX <3 you are my hero :)

**Comment by kriztan** [comment]
@philipflohr I've added your PR, can you please try to change your previously, with your patch, changed avatar after publishing again? I didn't get it working. At the moment I can't provide ADB logs, but I'll look into today evening.

**Comment by philipflohr** [comment]
@kriztan Is this your Testcase? Change avatar -> crop image -> publish avatar -> same procedure again?

Works for me. Or did I get something wrong?

**Comment by kriztan** [comment]
@philipflohr yes, right, this is my test case. I've figured out, that it is only working if I swipe conversations away from last used apps and restarting conversations -> change avatar -> and so on...

Please try as follows: go into manage accounts -> change avatar -> crop image -> publish avatar -> go back to manage accounts (don't close conversations) -> change avatar again isn't working, the crop image activity doesn't start until you close it and swipe it away from last used apps.

**Comment by philipflohr** [comment]
@kriztan I just tried it, in my phone the activity ist starting again. Do you have geh same behavior with the current Conversations release? Because my patch does not modify activity startup or termination code.

**Comment by kriztan** [comment]
@philipflohr 
I've tried it several times, with the image picker from android and the gallery app and figured out, that it is working as expected in the following cases:
1. start Conversations -> manage accounts --> avatar can be changed with gallery app
2. start Conversations -> manage accounts --> avatar can be changed with image picker

But if you don't close Conversations in the meantime and want to change the avatar again you have to use the app which you have used before (under 1. or 2.). For example you picked an image with the gallery app, the avatar could only be changed again with the gallery app. Using the image picker isn't working until you close Conversations, swipe it away from last used apps and start changing avatar. It doesn't matter if you use the gallery app first or the image picker.

**Comment by philipflohr** [comment]
I don't habe this behaviour - most likly because I have only one image picking App installed. But is the behavior different compared to the current Conversations release?

**Comment by kriztan** [comment]
Yes, with Conversations without this avatar crop patch it's working as expected, also with different image picking apps/galleries. Perhaps it is necessary to finish the cropping activity after publishing the avatar?

**Comment by philipflohr** [comment]
In this case this seems to be an issue with the android-crop library.

I'll check if there is a simple workaround.

**Comment by philipflohr** [comment]
I have changed the code to use a choose file intent instead of using android-crop's imagepicker function.
This is how choosing the avatar picture was done before.

On my device everything works as expected. 
@kriztan can you verify the behaviour with your device?

**Comment by kriztan** [comment]
@philipflohr Thanks, now it is working as expected.

**Comment by kriztan** [comment]
@philipflohr I've tried around with your PR and figured out, that big images (~18 MPixel and 10 MB) crashes Conversations with an `OutOfMemoryError`. I think it would be useful to scale the source image to e.g. device screen size to show the preview instead of loading the source file to preview. 

`java.lang.OutOfMemoryError
at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:620)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:596)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:634)
at android.provider.MediaStore$Images$Media.getBitmap(MediaStore.java:806)
at eu.siacs.conversations.ui.PublishProfilePictureActivity.loadImageIntoPreview(PublishProfilePictureActivity.java:237)
at eu.siacs.conversations.ui.PublishProfilePictureActivity.onBackendConnected(PublishProfilePictureActivity.java:208)
at eu.siacs.conversations.ui.XmppActivity$2.onServiceConnected(XmppActivity.java:160)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1101)
at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1118)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5034)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
at dalvik.system.NativeStart.main(Native Method)`

**Comment by philipflohr** [comment]
... there is an open bug in android-crop, Imagescaling does not work if .asSquare is used.
I'll fix this later

**Comment by philipflohr** [comment]
I updated my patch, the image is now scaled after cropping.
Works with the biggest jpeg I found (8000x8000 pixels)
@kriztan Can you verify that no OOM exeption is thrown on your device?

**Comment by kriztan** [comment]
@philipflohr Thank you for your fix, now it works without an OOM exception.

**Comment by kriztan** [comment]
@philipflohr I've to get on your nerves again. My wife tried to load a big image, after cropping the image, it returns back to the preview where you can publish the avatar, but this preview showes the old image. There where no errors shown. So I've tried a bit around, reduced the original image resolution and got it working after reducing the resolution. The original image has 16 MPixel - 8 MB, reducing it to 3 MPixel < 1 MB worked.

**Comment by philipflohr** [comment]
Hi,

for a reason I dont know, the current code only changes the Avatar, if the Backend ist connected. In my opinion only the availability of the publish button or the availablility if the imagepicker  should be bound to this. I kept the old behavior. Just wait for another minute and check if it works then.

**Comment by iNPUTmice** [comment]
Hi,

there is ````FileBackend.calcSampleSize(Bitmap.Options options, int size)```` you just have to change it to ````public static```` and you can avoid some duplicate code.

> for a reason I dont know, the current code only changes the Avatar, if the Backend ist connected.

I don't understand this. Can you point to a specific line of code were you find that condition?

Other than that. Thank you for your contribution. And can you squash / rebase this afterwards?

**Comment by philipflohr** [comment]
@iNPUTmice well, my code editing was some days ago and it was not the only one I did to Conversations, seems I got something wrong here.
@kriztan I can't reproduce this behaviour. Have you experienced it ever again?

**Comment by kriztan** [comment]
@philipflohr No I did not try it again until now and it was only happening with a big image file from a DSLR camera on an old Samsung Galaxy S2 which is more or less outdated. I think it is not the usual way to use such big files. With my newer Galaxy S3 it is working fine.

**Comment by iNPUTmice** [comment]
Maybe the loadScalledImage did throw an Exception which was caught. Might be worth displaying a Toast of some kind in that case.

also @philipflohr could you squash and rebase this?

**Comment by philipflohr** [comment]
I tested the current code with a 50MB png file from http://visibleearth.nasa.gov/view.php?id=74393 - works as expected on my device.
@iNPUTmice if there is an exception thrown by loadScaledImage, bm is null. This is checked one line below.

**Comment by iNPUTmice** [comment]
> @iNPUTmice if there is an exception thrown by loadScaledImage, bm is null. This is checked one line below.

ok. I missed that.

thanks and merged.

quick note: that code needed a tiny adjustment. Passing files didn't work for non-file uris such as the default avatar. Thats fixed in: 02c6793ca9ae195494c7be86f7e0d7a6c08a04c0

**Pull request merged**
