### PR TITLE
Some changes to the LED color in notifications !

### PR DESCRIPTION
**Pull request by QuentinC**
A little change to the LED color code. 
Making this will allow the led to work correctly on xperia devices !

### CODE REVIEW

**Comment by iNPUTmice** [comment]
This pull request also changes the color and the duration? Is this what is required for xperia devices to work? Can they not just display white light?

**Comment by QuentinC** [comment]
No, only the first line is required, but a green light feels better for me as many applications already use a white led color! 

Quentin Canel
Eleve-Ingénieur ISAE-ENSMA
Option Informatique et Avionique 
40 Allée Henri Guillaumet
77350 Le Mée sur Seine
France
06.70.37.34.65

---- Daniel Gultsch a écrit ----

**Comment by iNPUTmice** [comment]
Hi,

can you separate your actual bug fix `mBuilder.setDefaults(0);` from your changes of personal preferences and create (by squashing) a pull request that only contains the actual bug fix?

However I'm willing to do some experiments with duration and color. (Should be the Conversations green though instead of regular green)

**Comment by iNPUTmice** [comment]
thank you!

**Pull request merged**
