### PR TITLE
fix-3264:fix incomplete message notification displayed on notification drawer

### PR DESCRIPTION
**Pull request by marveljy**
#3265 Change: complete message notification displayed on the notification drawer to prompt user latest message content and received message count.

### CODE REVIEW

**Comment by licaon-kter** [comment]
Why edit build.gradle? Fix whatever error

**Comment by marveljy** [comment]
> Why edit build.gradle? Fix whatever error

Because there was an error when I submitted the previous version to check. So I followed the guide to modify build.gradle to make all checks pass.
image

**Comment by licaon-kter** [comment]
Why not fix the error in the first place?

**Comment by licaon-kter** [comment]
The error that forces you to force gradle to "ignore errors"...that one. :)

**Comment by marveljy** [comment]
> The error that forces you to force gradle to "ignore errors"...that one. :)

Sorry, I modified the code to fix #3264 and built it on my computer successfully, but I submitted it and then found some error existing. I tried to locate the bug by reading the report and think the error is caused by build config so that to modify the build.gradle. I will find the real bug location in code and try to fix it. I'm sorry to wrongly modify gradle.

**Comment by iNPUTmice** [comment]
Can you make that PR without touching build.gradle?

**Pull request closed without merging**
