### PR TITLE
PGP fix

### LINKED ISSUE #1568: Conversations crashes instantly after PGP-Key was assigned, NullPointerException at eu.siacs.conversations.crypto.PgpEngine$1.onReturn(PgpEngine.java:53)
And it continues crashing when device and application are restarted. Observed with conversations 1.7.2 on Android 6.

...
11-14 06:38:38.164   853  1279 W PackageManager: Unknown permission com.majeur.launcher.permission.UPDATE_BADGE in package eu.siacs.conversations
11-14 06:38:40.937   853   868 I ActivityManager: Start proc 1772:eu.siacs.conversations/u0a101 for broadcast eu.siacs.conversations/.services.EventReceiver
11-14 06:38:43.954  1772  1772 E AndroidRuntime: FATAL EXCEPTION: main
11-14 06:38:43.954  1772  1772 E AndroidRuntime: Process: eu.siacs.conversations, PID: 1772
11-14 06:38:43.954  1772  1772 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'eu.siacs.conversations.entities.Account eu.siacs.conversations.entities.Contact.getAccount()' on a null object reference
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at eu.siacs.conversations.crypto.PgpEngine$1.onReturn(PgpEngine.java:53)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at org.openintents.openpgp.util.OpenPgpApi$OpenPgpAsyncTask.onPostExecute(OpenPgpApi.java:232)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at org.openintents.openpgp.util.OpenPgpApi$OpenPgpAsyncTask.onPostExecute(OpenPgpApi.java:213)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:651)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-14 06:38:44.007   853  1539 I ActivityManager: Process eu.siacs.conversations (pid 1772) has died
11-14 06:38:44.008   853  1539 W ActivityManager: Scheduling restart of crashed service eu.siacs.conversations/.services.XmppConnectionService in 1000ms
...

I attached a more complete log, created by replacing the account and server-names and doing a  grep "4734\|conversations\|1772". The server used was not example.net but jabber.at.

[conversation2a.txt](https://github.com/siacs/Conversations/files/34567/conversation2a.txt)

### PR DESCRIPTION
**Pull request by fiaxh**
Should fix #1568 and #1544.

@lupusmeatus @Polynomdivison @halemmerich : Can you confirm that this solves your problem?

### CODE REVIEW

**Comment by Polynomdivison** [comment]
Assign PGP Keys and encrypt Chat in MUC is working with this fix. :+1: 

But when you want to encrypt a picture (same for voice and file) in MUC there is a message that conversations is not able to find a pgp key for the contact. Sending text messages is working.

Thanks. :)

Sending a picture creates this:

    11-15 16:17:47.453 19186-19210/eu.siacs.conversations W/MALI: glDrawArrays:714: [MALI] glDrawArrays takes more than 5ms here. Total elapse time(us): 6295
    11-15 16:17:52.857 19186-19186/eu.siacs.conversations D/FeatureProxyBase: FeatureProxyBase class constructor
    11-15 16:17:52.857 19186-19186/eu.siacs.conversations D/MultiWindow: MultiWindowProxy constructor.
    11-15 16:17:52.857 19186-19186/eu.siacs.conversations D/FeatureProxyBase: getService(), serviceName = multiwindow_service_v1
    11-15 16:17:52.945 19186-19186/eu.siacs.conversations V/SettingsInterface:  from settings cache , name = sound_effects_enabled , value = 0
    11-15 16:17:52.946 19186-19186/eu.siacs.conversations D/FeatureProxyBase: FeatureProxyBase class constructor
    11-15 16:17:52.947 19186-19186/eu.siacs.conversations D/MultiWindow: MultiWindowProxy constructor.
    11-15 16:17:52.947 19186-19186/eu.siacs.conversations D/FeatureProxyBase: getService(), serviceName = multiwindow_service_v1
    11-15 16:17:52.948 19186-19186/eu.siacs.conversations D/FeatureProxyBase: FeatureProxyBase class constructor
    11-15 16:17:52.948 19186-19186/eu.siacs.conversations D/MultiWindow: MultiWindowProxy constructor.
    11-15 16:17:52.948 19186-19186/eu.siacs.conversations D/FeatureProxyBase: getService(), serviceName = multiwindow_service_v1
    11-15 16:17:52.967 19186-19186/eu.siacs.conversations D/ViewRootImpl: hardware acceleration is enabled, this = ViewRoot{302108d2 eu.siacs.conversations/eu.siacs.conversations.ui.ConversationActivity,ident = 83}
    11-15 16:17:52.974 19186-19186/eu.siacs.conversations D/Dialog: show
    11-15 16:17:53.004 19186-19210/eu.siacs.conversations D/OpenGLRenderer: CanvasContext() 0xef833080 initialize 0xe1efd208
    11-15 16:17:53.004 19186-19210/eu.siacs.conversations D/Surface: Surface::connect(this=0xe1efd200,api=1)
    11-15 16:17:53.005 19186-19210/eu.siacs.conversations D/mali_winsys: new_window_surface returns 0x3000
    11-15 16:17:53.005 19186-19210/eu.siacs.conversations D/Surface: Surface::allocateBuffers(this=0xe1efd200)
    11-15 16:17:53.016 19186-19210/eu.siacs.conversations D/GraphicBuffer: register, handle(0xdf5e10c0) (w:812 h:738 s:816 f:0x1 u:0x000b00)
    11-15 16:17:53.034 19186-19210/eu.siacs.conversations D/GraphicBuffer: register, handle(0xefb4f020) (w:812 h:738 s:816 f:0x1 u:0x000b00)
    11-15 16:17:53.041 19186-19186/eu.siacs.conversations D/AbsListView: onWindowFocusChanged: hasWindowFocus=false, this=de.timroes.android.listview.EnhancedListView{15a0ff11 VFED.VC. ........ 0,0-608,914 #7f0e00bd app:id/list}
    11-15 16:17:53.043 19186-19186/eu.siacs.conversations D/AbsListView: onWindowFocusChanged: hasWindowFocus=false, this=android.widget.ListView{a9f6b26 VFED.VCL ........ 0,0-720,1021 #7f0e00b5 app:id/messages_view}
    11-15 16:17:53.043 19186-19186/eu.siacs.conversations V/TextView: stopSelectionActionMode()
    11-15 16:17:53.043 19186-19186/eu.siacs.conversations V/TextView: stopSelectionActionMode()
    11-15 16:17:53.043 19186-19186/eu.siacs.conversations V/TextView: stopSelectionActionMode()
    11-15 16:17:53.044 19186-19186/eu.siacs.conversations V/TextView: stopSelectionActionMode()
    11-15 16:17:53.044 19186-19186/eu.siacs.conversations V/TextView: stopSelectionActionMode()
    11-15 16:17:54.201 19186-19210/eu.siacs.conversations D/GraphicBuffer: register, handle(0xef88a340) (w:812 h:738 s:816 f:0x1 u:0x000b00)

**Comment by fiaxh** [comment]
@Polynomdivison Thanks for testing.

>But when you want to encrypt a picture (same for voice and file) in MUC there is a message that conversations is not able to find a pgp key for the contact. Sending text messages is working.

I can confirm that, however the problems are not related (Conversation tries to find the key-ID belonging to the MUC contact, which of course does not exist). You could open an issue for that.

**Comment by halemmerich** [comment]
The fix resolves the NullPointer crash problem for me. I could however not test completely because on my device (AOSP 5.1 with several xposed modules) sending in mucs is seemingly ignored (besides crashing before this fix). I have to investigate further what causes this.
I also can confirm the encrypted file issue, but this behaviour has been that way a long time.

**Comment by Polynomdivison** [comment]
I created a new issue for sending encrypted files via muc:
 #1575

**Pull request merged**
