### PR TITLE
Updated languages ...

### PR DESCRIPTION
**Pull request by kriztan**
... for higher auto accept file sizes and changed labeling to MiB and KiB

### CODE REVIEW

**Comment by iNPUTmice** [comment]
> /home/travis/build/siacs/Conversations/src/main/res/values-es/arrays.xml:24:22: Error: The element type "resources" must be terminated by the matching end-tag "</resources>".

Thank you but could you fix that build error and squash?

**Comment by kriztan** [comment]
Should be fixed now

**Comment by iNPUTmice** [comment]
Ok thank you. travis says its working now. But you squash this very quickly? (Have one commit instead of 17?)

**Comment by kriztan** [comment]
I think it is squashed now...

**Pull request merged**
