### PR TITLE
add ui emoji button

### PR DESCRIPTION
**Pull request by SoyaLeaf**
#2759 
image

### CODE REVIEW

**Comment by licaon-kter** [comment]
Pics?

**Comment by SoyaLeaf** [comment]
Hi,
I did not find something similar to the code specification,should we refer to a unified standard? I'm afraid my code is not standardized enough to make the code look messy...But I can only try to reference other people's code style...

Then I wondered if such a display would make people feel weird...
@licaon-kter @iNPUTmice

**Comment by licaon-kter** [comment]
Whatis that horizontal bar above text input?

**Comment by SoyaLeaf** [comment]
Because emoji is too much, I define some anchors based on the emoji theme,this one is used to reach these anchors quickly. @licaon-kter

**Comment by uchchishta** [comment]
I think categories are standardized see [emojipedia](https://emojipedia.org) 
Try ` 🕓  😎  🌼  🍉  🚀  ⚽  🔔  🔷  🚩`

**Comment by SoyaLeaf** [comment]
Sorry to bother，but I would like to know ,

- it is because the project doesn't need this feature?
- or my code is not clean enough?
- or because it is submitted too much commit so that it is not convenient to view

This determines whether I continue to try to modify it. In my opinion, this button is necessary, although it does not look perfect now.

Regarding the third point, when I created the PR, that was not the case. I don't know why it became this way and I remember you reminded me of this...

Maybe bother you，apologize again. :)

@iNPUTmice

**Comment by iNPUTmice** [comment]
Hi,

this PR was automatically closed by Github because I deleted the app_compat branch. The changes should apply more or less cleanly on top of the current master branch though. app_compat basically became master.

**Comment by SoyaLeaf** [comment]
em...Thanks for the answer. @iNPUTmice 

This pr is not perfect, I think it is not ready to be merged yet. I would like to listen to the opinions of others, and then make changes, and then I will perfect this feature in my spare time. Maybe the process of change will be a bit long...

**Comment by iNPUTmice** [comment]
I think design wise the emojis should be closer together and a bit larger. And maybe replace the keyboard instead of chat view. (like this is done in WhatsApp and probably other messengers)

**Comment by SoyaLeaf** [comment]
@uchchishta Thanks for your advice 👍

**Pull request closed without merging**
