### PR TITLE
[WIP] XEP-0224: Attention support

### PR DESCRIPTION
**Pull request by BlauerHunger**
**WIP, do not merge!**

## TODO

- [x] Icon for entry in attachment menu
- [ ] Show "request attention" only in 1:1 conversations
- [ ] Show information that attention requests are not reliable
- [x] Show that the message is an attention request in notification
- [x] Add preference to set whether notifications for attention requests should have a higher priority

### CODE REVIEW

**Comment by wiktor-k** [comment]
Do attention messages override Conversations' silent hours? I'd be good if they did that for roster contacts that want to send some urgent message.

**Comment by BlauerHunger** [comment]
At the moment they're just a ❗ next to the message.

**Comment by wiktor-k** [comment]
Oh I see, I frequently get phone calls from my important contacts because their Conversations messages are muted in silent hours and I think Attention would most certainly help here.

**Comment by wiktor-k** [comment]
It can override Conversations' own silent hours, for me that's sufficient as I can whitelist Conversations in Android. (I don't know if stock Android has silent hours app whitelisting).

**Comment by mzmitrulevicius** [comment]
is it possible to change attention sound?

**Comment by licaon-kter** [comment]
@mzmitrulevicius use your Android settings?

**Comment by mzmitrulevicius** [comment]
@licaon-kter yes i wanna that attention sound be different from notification

**Comment by mzmitrulevicius** [comment]
@licaon-kter But notification sound works perfectly i just whant that when it receives attention it would be alarm sound not default notification sound

**Comment by mzmitrulevicius** [comment]
I'm almost done it, it alarms different way when message priority is max, but it does only when app is open, can someone tell me how to do the same when app is in background?


        public int priority(Builder mBuilder, boolean attention) {
        SharedPreferences preferences = PreferenceManager.getDefaultSharedPreferences(mXmppConnectionService);
        final Resources resources = mXmppConnectionService.getResources();
        final String ringtone = preferences.getString("attention_ringtone", resources.getString(R.string.attention_ringtone));
        final boolean headsup = preferences.getBoolean("notification_headsup", resources.getBoolean(R.bool.headsup_notifications));
        final boolean important = preferences.getBoolean("notification_attention_priority", resources.getBoolean(R.bool.attention_priority));

        int priority;

        if (headsup && (important && attention)) {
            priority = NotificationCompat.PRIORITY_MAX;
            Uri uri = Uri.parse(ringtone);
            try {
                mBuilder.setSound(fixRingtoneUri(uri));
            } catch (SecurityException e) {
                Log.d(Config.LOGTAG, "unable to use custom notification sound " + uri.toString());
            }
        } else if (headsup ^ (important && attention)) {
            priority = NotificationCompat.PRIORITY_HIGH;

        } else {
            priority = NotificationCompat.PRIORITY_DEFAULT;
        }

        return priority;
    }
>

**Pull request closed without merging**
