### PR TITLE
WIP: Add fastlane screenshots and localized descriptions

### PR DESCRIPTION
**Pull request by mimi89999**
This is mostly for F-Droid.

@iNPUTmice If you are OK with that I will add translations and maybe better screenshots.

### CODE REVIEW

**Comment by iNPUTmice** [comment]
Is there documentation on fdroid using fastlane?

**Comment by mimi89999** [comment]
@iNPUTmice https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots/

**Comment by licaon-kter** [comment]
Any update on this?

**Comment by licaon-kter** [comment]
Funny that the fork has better support https://f-droid.org/en/packages/eu.sum7.conversations/ :(

**Comment by iNPUTmice** [comment]
Fixed in 1008bf405ea778685526fcf1b7b8cdb063a9f94e

**Pull request closed without merging**
