### PR TITLE
make a larger cursor window size.

### PR DESCRIPTION
**Pull request by hochwasser**
This pull request was created on request of @iNPUTmice 
This is a patch as suggested at https://stackoverflow.com/questions/51959944/ 
I don't know what this does and why the cursor window size was changed in Pie.
Also I don't know if this change must be applied to other ` cursor.moveNext() ` in the file.
The ticket to this problem is #3566

### CODE REVIEW

**Comment by iNPUTmice** [comment]
If I’m understanding you correctly you seem to have a local backup that triggers the bug. Do you mind checking the recent master on whether or not it fixes your issue?

**Comment by hochwasser** [comment]
You are correct. A friend of mine showed me how to make a backup with adb and how to get the database into the emulator. 
I will try to check the master and give you response

**Comment by hochwasser** [comment]
8k are not enough for my database. With 80k it works. I can't figure out why and what they changed in Android Pie. In the release note I found nothing. Has someone a description of the window feature by hand?
So I can not say if 80k is enough for others or if there are databases which even needs higher values.

**Comment by hochwasser** [comment]
I tried to change my patch. Is this so acceptable?

**Comment by iNPUTmice** [comment]
Have you tried intermediate values between 8 and 80?
And no; unfortunately this is not acceptable in the current form; first of all 80 is way too high for a general audience; and secondly as you said yourself - it might not be enough for everyone.

**Comment by hochwasser** [comment]
Hello iNPUTmice, I have to say, that I do not understand the cursor thing of API level 28. I would really like to understand this thing and why there is nothing in the release note.

Now the size will be made bigger in 1k steps and if 1M is reached it will break as it does not make any sens to make it bigger.
With my database a 65k cursorwindow is needed that it works.
Is this good enough for you?

**Comment by hochwasser** [comment]
What I forgot at 2 o'clock: The 65k where needed only for one "Conversation". All other work fine with 1k.
I did not find out what was so special about this.

**Comment by hochwasser** [comment]
I tried my best at sqlite and came up with this query:
`SELECT SUM(LENGTH(body)) FROM messages WHERE conversationUuid='XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' ORDER BY timeSent DESC LIMIT 50`
```
SUM(LENGTH(body))|
-----------------|
            39529|
```
If the query is correct, the result is ... big.
The body column alone is ~40k

**Comment by iNPUTmice** [comment]
@hochwasser can you do that for the other columns. In particular `edited` and `readByMarkers` - because while your output is helpful it doesn’t explain why it fails.

(For clarification; I mislabel the CursorWindow size. It is currently set to 8MB. Not 8k. Meaning bodies of an accumulated size of 40k should easily fit in there.

**Comment by hochwasser** [comment]
If these are no kilo byte but mega bytie then I don't know why the query needs 65MB. As I said: 1MB is enough for all but one query.
This is really strange.

**Comment by hochwasser** [comment]
Here are the measurements:
```
SUM(LENGTH(body))|SUM(LENGTH(edited))|SUM(LENGTH(readByMarkers))|
-----------------|-------------------|--------------------------|
            39529|            2098438|                       990|
```
I hope this helps

**Comment by iNPUTmice** [comment]
@hochwasser it actually does. Thank you.

**Comment by iNPUTmice** [comment]
Thanks. This should be properly fixed now; Without increasing the CursorWindow

**Pull request closed without merging**
