### PR TITLE
Implemented account registration with captcha

### PR DESCRIPTION
**Pull request by akallabeth**
* Fixes issue #308 
* Captcha request / submit compatible with pidgin captcha handling. 
* Displays the captcha scaled to the current text scaling factor (it is assumed the image has text to display, so it is likely to require the same scaling)

Since I've only tested with limited resources, I'd welcome further testing before merging.

### CODE REVIEW

**Comment by iNPUTmice** [comment]
Thanks

will test this asap.

**Comment by iNPUTmice** [comment]
Hi,

working as expected at least with the one server I tested this with.

However the code needs some clean up. First of all the method ```submitRequestedCaptcha``` is never being called.

Secondly I noticed you are passing along a lot of information like url, challange and so forth as individual parameters through the various stages. It might be easier to just pass along the actual data element. With that in the last step you even avoid recreating the a new data object and filling it with the passed-along information but instead submit the captcha text to the original form, call data.submit() on it and push that back to the server.

Thirdly I feel that the negative callback (what happens when the user presses cancel on the dialog) can be merged into the the same callback as the success. And have let the data variable be NULL to indicate a failure. That reduces the number of methods needed for that change.

**Comment by akallabeth** [comment]
@iNPUTmice Ok, changed the pull according to your suggestions.
I've noticed an issue though, while the captcha dialog is shown the registration process is retried in background. That way it is possible to get multiple stacked capcha dialogs. Is there an easy way to suspend registration retries until the user has responded?

**Comment by iNPUTmice** [comment]
> That way it is possible to get multiple stacked capcha dialogs. Is there an easy way to suspend registration retries until the user has responded?

No that is unfortunately not possible without major refactoring. (I will take that on later though. Might be usefull for stuff like TLS certificates as well)

Either way. Even if we would do that I would still build a mechanism that closes the dialog and calls the callback with failed/canceld once the listener gets removed.

One more thing. You seem to be fetching the bitmap on the UI thread under some conditions. captcha == null. What are those cases and can we work around sound. Downloading the image on the UI thread is not a good idea.

**Comment by akallabeth** [comment]
Oh, well, really unfortunate.

As for the Bitmap, yes I can move that. It is just a fallback mechanism fetching the bitmap from the URL in case it was not inlined.

**Comment by iNPUTmice** [comment]
>  It is just a fallback mechanism fetching the bitmap from the URL in case it was not inlined.

oh so the server can decide wether do send the bitmap inband or just provide a link?

either way that should be fetched on the network thread.

**Comment by iNPUTmice** [comment]
Hi thank you

couple of more remarks

* I think it is enough if EditAccountDetails implements the Captcha Dialog. because a) In most cases you will be presented with the Captcha on First try anyway. b) random, out-of-context pop-ups in other places of the app will confuse the user.
* As a consequence the Dialog Creation can be moved into EditAccountDetails
* The Dialog should set an OnCancelListener as well to reject the captcha if the user closes the dialog without clicking the cancel button.
* You can do something like this:
````
if (this.mCaptchaDialog != null && this.mCaptchaDialog.isShowing()) {
    this.mCaptchaDialog.dismiss();
}
final AlertDialog.Builder builder = new AlertDialog.Builder(this);
....
this.mCaptchaDialog = builder.create();
this.mCaptchaDialog.show();
````
to work around the multiple dialog problem you mentioned.
* Matter of personal taste. I don't like the warning icon. Could you remove ````builder.setIconAttribute(android.R.attr.alertDialogIcon);````
* The captcha null check during the dialog creation is redundant I think. Removing that will clean up the code.

**Comment by iNPUTmice** [comment]
Also see me last commit ef605e4cbd162d48e40d13d91b188b9838de308d that prevents the Edit Account Activity from closing if we are still in the process of registering an account (aka if there might be a captcha request incoming)

**Comment by akallabeth** [comment]
@iNPUTmice Ok, rebased the branch and changed the handling as requested. As for preventing EditAccountActivity being closed is that really a good idea? It would prevent aborting account creation if I understand that correctly.

**Comment by iNPUTmice** [comment]
> Ok, rebased the branch and changed the handling as requested

Thanks. I'll have a look

> As for preventing EditAccountActivity being closed is that really a good idea? It would prevent aborting account creation if I understand that correctly.

Oh no. Sorry. 'Preventing from closing automatically' I mean. Doesn't matter. If you didn't encounter that 'bug' and don't know what I'm talking about then never mind.

**Pull request merged**
