### PR TITLE
add delivery receipts for private muc msgs & enable update last-seen for muc-msgs

### PR DESCRIPTION
**Pull request by BrianBlade**
Please consider as follow-up on https://github.com/siacs/Conversations/pull/1035 and double-check the changes.

Thanks!

### CODE REVIEW

**Comment by iNPUTmice** [comment]
Hi,

this was actually part of your first PR as well but I didn't saw it then or I would have spoken up about this before you went through the trouble of squasing. But MessageParser.java:68ff basically duplicates lines that already exist.

And is there a reasons for the changes in XmppConnectionService? If so I think they should be part of a seperate commit because they are unrelated to what you are trying to do.

**Comment by BrianBlade** [comment]
Hi and thanks for your prompt response,

Yes, these lines in 68 seem needless, I somehow didnt spot that.

Regarding the change in XmppConnectionService: Its related to marking private MUC-messages. A MUC-Conversation returns (at least some times?) a fullJid and I need to remove the resourcepart to identify potential locations of the to-be-marked message. I deemed it less risky to just suppress the resourcepart in markMessage() compared to changing the Conversation.contactJid.
Please correct me if I got somethin wrong or if you can come up with a more appropriate solution. I am positive that I will get the squashing right next time ;)

**Comment by iNPUTmice** [comment]
Ok thank you.
I will test the findConversation patch to see if this has any side effects. But you might be right.

Two minor things left:
* MessageParser.java:72 - you can use the variable trueCounterpart here instead of translating the user into the real jid again.
* MessageParser.java:173 has two tabs indention

Thank you for your contribution.

**Comment by BrianBlade** [comment]
Well, thank you for your patience and for developing Conversations!

**Comment by iNPUTmice** [comment]
Ok. Merged and thank you!

**Pull request merged**
