### PR TITLE
Add feature to change contact-wise message color

### PR DESCRIPTION
**Pull request by harshitbansal05**
This feature tries to solve #2065. It provides the feature to change contact-wise message background color. For this, a color palette is shown consisting of some colors. The color palette is shown by importing the google's open source module https://android.googlesource.com/platform/frameworks/opt/colorpicker/ in the repository. The `default` or `reset` feature also needs to be added, but I could not find a proper style for doing so. So, I created this to gain feedback on that..

### CODE REVIEW

**Comment by licaon-kter** [comment]
> It provides the feature to change

Pfft, not yet ?!

**Comment by licaon-kter** [comment]
I'm not seeing an option...where should I look?

**Comment by harshitbansal05** [comment]
long tap the receiver message, sorry I forgot to mention that..

**Comment by myluckyapps** [comment]
So long tap worked fine :-)
I was wondering where to find the color of contacts :-)

Also it working fine in MUC too.

**Comment by myluckyapps** [comment]
I have tested these changes, But I am experiencing few chat bubbles are not showing selecting colors few of them still in green.  I am testing in Samsung 6.

**Comment by licaon-kter** [comment]
@myluckyapps Are those special in any way?

**Comment by myluckyapps** [comment]
Sorry my bad. I didnot notice the green colors are from different user. It look fine. 

[https://i0.wp.com/sollu.files.wordpress.com/2018/04/screenshot_20180413-001226.png?ssl=1&w=450](url)

**Comment by licaon-kter** [comment]
@harshitbansal05 I was thinking of a simplification, since Conversations already generates colours per JID for the included letter avatars, how about you use that colour, without the need to import "a colour picker" and such?

**Comment by harshitbansal05** [comment]
@licaon-kter, I would not waste my time on this as the owner barely pays any attention.

**Comment by licaon-kter** [comment]
Yes and no, look at the current PR: adds ~100 files from another project (colour picker) that needs to be maintained, adds 200 more lines of code.

While my idea above _seems_ doable even by me (I'm no dev but I'll try to find some time to tackle this) since we only need to grab the colour calculated elsewhere in the app and apply that.

**Comment by harshitbansal05** [comment]
@licaon-kter not complaining, but a pull request is always open for reviews. If you or someone else had expressed their views regarding the size of the library, I would have made the custom color palette by myself without the library, very similar to the work done by me in another pull request. Just ignoring and leaving the pull request  as it is seems no solution to me.
Nevertheless, I would try to find some time for the work.

**Comment by licaon-kter** [comment]
Not complaining either, I didn't think of the included colour thing and your solution is kinda better, from an user perspective.

Maybe if the lib can be used from maven and not directly included the burden is smaller (future Android compatibility etc)

**Comment by iNPUTmice** [comment]
We are following the XEP consistent color generation.

**Pull request closed without merging**
